Repository acm-ucr/tag-website, pull requests merged in 2024-04, with the labels that each got.

#25 implemented circles
  src/app/page.js
  src/components/Circles.jsx
  src/components/Hero.jsx
  tailwind.config.js
Labels: Ready for Review, Front End

#26 Created Navbar
  src/components/Navbar.jsx
Labels: Ready for Review, Front End

#27 Created Board Component
  src/components/Board.jsx
  src/components/Card.jsx
  src/data/board.js
Labels: Ready for Review, Front End

#35 Added rules section for Go
  src/components/GoRules.jsx
  src/components/Rules.jsx
Labels: good first issue, Ready for Review, Front End

#43 added gallery section
  src/app/layout.js
  src/app/photos/page.js
  src/components/Gallery.jsx
Labels: Ready for Review, Front End

#33 Added about me component
  src/components/About.jsx
Labels: Ready for Review

#37 adding footer
  src/components/Footer.jsx
  src/components/GoRules.jsx
  src/components/Navbar.jsx
  tailwind.config.js
Labels: Ready for Review, Front End

#52 Centered text and added padding
  src/components/Rules.jsx
Labels: bug, Front End

#51 Created Title Component
  src/components/Button.jsx
  src/components/Hero.jsx
  src/components/Title.jsx
Labels: Ready for Review, Front End

#49 Created Mahjong rules
  src/components/GoRules.jsx
  src/components/MahjongRules.jsx
  src/components/Rules.jsx
Labels: Ready for Review, Front End

#29 created header component
  src/app/board/page.js
  src/app/events/page.js
  src/app/photos/page.js
  src/components/Header.jsx
  src/components/Hero.jsx
  src/components/Title.jsx
Labels: Ready for Review

#59 enchanced about section
  src/components/About.jsx
Labels: Ready for Review, Front End

#61 Fixed design issue with bar
  src/components/MahjongRules.jsx
Labels: Ready for Review, Front End, Design fix

#62 Designed ring around Go circle a lighter shade of green
  src/components/Circles.jsx
Labels: Ready for Review, Front End, Design fix

#64 Get Connected/Icons
  src/components/Connect.jsx
  src/components/Rules.jsx
Labels: good first issue, Ready for Review, Front End

#65 hover icons
  src/app/layout.js
  src/components/Footer.jsx
Labels: enhancement, Ready for Review, Front End

#63 Arieen17/board photos
  public/Rong.webp
  src/app/board/page.js
  src/components/Board.jsx
  src/components/Card.jsx
  src/components/Header.jsx
  src/data/board.js
Labels: Ready for Review
