Repository acm-ucr/tag-website, pull requests merged in 2024-05, with the labels that each got.

#75 Arieen17/about responsiveness
  src/components/About.jsx
Labels: Ready for Review

#76 changed the header size for different screens
  src/components/Header.jsx
Labels: Ready for Review, Responsiveness

#72 Created Links for Connect Bubbles
  src/components/Connect.jsx
Labels: enhancement, Ready for Review, Front End

#74 (attempted to add) added responsiveness for footer
  src/components/Footer.jsx
Labels: Ready for Review, Front End, Design fix, Responsiveness

#78 Adding responsiveness
  src/components/GoRules.jsx
  src/components/MahjongRules.jsx
Labels: Ready for Review, Front End, Responsiveness

#73 implemented responsiveness hero section
  src/components/Circles.jsx
  src/components/Hero.jsx
  src/components/Title.jsx
Labels: Ready for Review, Do Not Merge, Front End, Responsiveness

#79 Tried Making Connect Section Responsiveness
  src/components/Connect.jsx
Labels: Front End, Design fix, Responsiveness

#85 Adjusted text and added flex-col-reverse
  src/components/GoRules.jsx
  src/components/MahjongRules.jsx
Labels: bug, Ready for Review, Design fix

#86 Added responsiveness for middle bar
  src/components/Footer.jsx
Labels: help wanted, Front End, Responsiveness
